"use strict";
/* Port of the repo's posture/ package: view, metrics, uncertainty, guards,
   verdicts, and the plain-language report (posture/report.py).

   `C` is generated by scripts/build_web.py from the Python side: noise model,
   thresholds, guard constants and the consumer copy (posture/consumer_zh.json).
   That script also runs this file under node over every test photo and fails
   the build if anything -- view, guards, readings, uncertainties, bands, or
   the report a person reads -- differs from Python. */
const NOSE=0,LEYE=2,REYE=5,LEAR=7,REAR=8,LSH=11,RSH=12,LWR=15,RWR=16,
      LHIP=23,RHIP=24,LKNEE=25,RKNEE=26,LANK=27,RANK=28;
const NAMES=["nose","left_eye_inner","left_eye","left_eye_outer","right_eye_inner","right_eye",
"right_eye_outer","left_ear","right_ear","mouth_left","mouth_right","left_shoulder","right_shoulder",
"left_elbow","right_elbow","left_wrist","right_wrist","left_pinky","right_pinky","left_index",
"right_index","left_thumb","right_thumb","left_hip","right_hip","left_knee","right_knee",
"left_ankle","right_ankle","left_heel","right_heel","left_foot_index","right_foot_index"];
const EDGES=[[7,2],[2,0],[0,5],[5,8],[11,12],[11,13],[13,15],[12,14],[14,16],[11,23],[12,24],
[23,24],[23,25],[25,27],[27,31],[24,26],[26,28],[28,32]];
const CRIT=[LEAR,REAR,LSH,RSH,LHIP,RHIP,LANK,RANK];
const DIAG=new Set(C.diagnostic_only);

const D=Math.PI/180, deg=r=>r/D;
const px=(P,i)=>({x:P[i][0],y:P[i][1]}), vis=(P,i)=>P[i][2];
const dist=(a,b)=>Math.hypot(b.x-a.x,b.y-a.y);
const mid=(a,b)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});
const angV=(lo,up,ant)=>deg(Math.atan2((up.x-lo.x)*ant,-(up.y-lo.y)));
function angH(l,r){let dx=r.x-l.x,dy=-(r.y-l.y);if(!dx&&!dy)return 0;
  let a=deg(Math.atan2(dy,dx));if(a>90)a-=180;else if(a<=-90)a+=180;return a;}
function angI(a,v,c){const v1={x:a.x-v.x,y:a.y-v.y},v2={x:c.x-v.x,y:c.y-v.y};
  const n1=Math.hypot(v1.x,v1.y),n2=Math.hypot(v2.x,v2.y);if(!n1||!n2)return NaN;
  return deg(Math.acos(Math.max(-1,Math.min(1,(v1.x*v2.x+v1.y*v2.y)/(n1*n2)))));}

function bodyScale(P,W,H){
  const sh=mid(px(P,LSH),px(P,RSH)), hip=mid(px(P,LHIP),px(P,RHIP));
  const inF=i=>{const p=px(P,i);return p.x>=0&&p.x<=W&&p.y>=0&&p.y<=H;};
  if(inF(LANK)&&inF(RANK)){const d=dist(sh,mid(px(P,LANK),px(P,RANK)));if(d>1)return d;}
  return dist(sh,hip)*2.6;  // shoulder-to-ankle is ~2.6x shoulder-to-hip
}
function sig(name,scale){const f=C.noise.per_landmark[name];return (f==null?C.noise.overall:f)*scale;}
const angSig=(sa,sb,span)=>span<=1e-6?NaN:deg(Math.hypot(sa,sb)/span);

function estimateView(P,W,H){
  const scale=Math.max(1,bodyScale(P,W,H));
  const lsh=px(P,LSH),rsh=px(P,RSH),lh=px(P,LHIP),rh=px(P,RHIP);
  const spread=Math.abs(lsh.x-rsh.x)/scale;
  const view=spread<=C.view.SIDE_MAX_SPREAD?"side":(spread>=C.view.FRONT_MIN_SPREAD?"front":"oblique");
  const nose=px(P,NOSE),em=mid(px(P,LEAR),px(P,REAR));
  const href=Math.max(dist(px(P,LEAR),px(P,REAR)),scale*0.06);
  const dx=nose.x-em.x;
  return {view,spread,facing:dx>=0?1:-1,conf:href>0?Math.min(1,Math.abs(dx)/href):0,
          hipSpread:Math.abs(lh.x-rh.x)/scale,scale};
}
function nearSide(P){
  const lv=vis(P,LEAR),rv=vis(P,REAR);let left;
  if(Math.abs(lv-rv)>0.15) left=lv>rv;
  else {const nx=px(P,NOSE).x;
        left=Math.abs(px(P,LEAR).x-nx)>Math.abs(px(P,REAR).x-nx);}
  return left?{ear:LEAR,sh:LSH,hip:LHIP,knee:LKNEE,ank:LANK}
             :{ear:REAR,sh:RSH,hip:RHIP,knee:RKNEE,ank:RANK};
}
const M=(key,val,unc,plane,span,idx)=>({key,val,unc,plane,span,idx});

function computeSagittal(P,V){
  const s=V.scale,S=nearSide(P),ant=V.facing,o={};
  const g=i=>sig(NAMES[i],s);
  const ear=px(P,S.ear),sh=px(P,S.sh),hip=px(P,S.hip),kn=px(P,S.knee),an=px(P,S.ank);
  let sp=dist(sh,ear);
  o.forward_head=M("forward_head",angV(sh,ear,ant),angSig(g(S.sh),g(S.ear),sp),"sagittal",sp,[S.sh,S.ear]);
  sp=dist(hip,sh);
  o.shoulder_protraction=M("shoulder_protraction",angV(hip,sh,ant),angSig(g(S.hip),g(S.sh),sp),"sagittal",sp,[S.hip,S.sh]);
  sp=dist(an,hip);
  o.trunk_sway=M("trunk_sway",angV(an,hip,ant),angSig(g(S.ank),g(S.hip),sp),"sagittal",sp,[S.ank,S.hip]);
  sp=dist(hip,ear);
  o.head_over_hip=M("head_over_hip",angV(hip,ear,ant),angSig(g(S.hip),g(S.ear),sp),"sagittal",sp,[S.hip,S.ear]);
  const inter=angI(hip,kn,an), legLen=dist(hip,an);
  if(legLen>1e-6&&!isNaN(inter)){
    const cross=(an.x-hip.x)*(kn.y-hip.y)-(an.y-hip.y)*(kn.x-hip.x);
    const sgn=(cross*ant)<0?1:-1, sp2=legLen/2;
    o.knee_deviation=M("knee_deviation",(180-inter)*sgn,angSig(g(S.knee),g(S.knee),sp2),"sagittal",sp2,[S.hip,S.knee,S.ank]);
  }
  o._near=S;
  return o;
}
function computeFrontal(P,V){
  const s=V.scale,o={},g=i=>sig(NAMES[i],s);
  const lsh=px(P,LSH),rsh=px(P,RSH),lh=px(P,LHIP),rh=px(P,RHIP),le=px(P,LEYE),re=px(P,REYE);
  let sp=dist(rsh,lsh);
  o.shoulder_tilt=M("shoulder_tilt",angH(rsh,lsh),angSig(g(RSH),g(LSH),sp),"frontal",sp,[RSH,LSH]);
  sp=dist(rh,lh);
  o.pelvis_tilt=M("pelvis_tilt",angH(rh,lh),angSig(g(RHIP),g(LHIP),sp),"frontal",sp,[RHIP,LHIP]);
  sp=dist(re,le);
  o.head_tilt=M("head_tilt",angH(re,le),angSig(g(REYE),g(LEYE),sp),"frontal",sp,[REYE,LEYE]);
  const shm=mid(lsh,rsh),hipm=mid(lh,rh);sp=dist(hipm,shm);
  if(sp>1e-6){const n=px(P,NOSE);
    o.lateral_head_shift=M("lateral_head_shift",deg(Math.atan2(n.x-shm.x,sp)),angSig(g(NOSE),g(LSH),sp),
      "frontal",sp,[NOSE,LSH,RSH]);}
  if(o.shoulder_tilt&&o.head_tilt){
    o.head_vs_shoulder_tilt=M("head_vs_shoulder_tilt",o.head_tilt.val-o.shoulder_tilt.val,
      Math.hypot(o.head_tilt.unc,o.shoulder_tilt.unc),"frontal",Math.min(o.head_tilt.span,o.shoulder_tilt.span),
      o.head_tilt.idx.concat(o.shoulder_tilt.idx));}
  return o;
}
function computeAll(P,V){
  let o={},near=null;
  if(V.view==="side"||V.view==="oblique"){const s=computeSagittal(P,V);near=s._near;delete s._near;Object.assign(o,s);}
  if(V.view==="front"||V.view==="oblique")Object.assign(o,computeFrontal(P,V));
  return {mets:o,near};
}
function outOfFrame(P,W,H){
  const m=C.guards.OUT_OF_FRAME_MARGIN*bodyScale(P,W,H),s=new Set();
  for(let i=0;i<33;i++){const p=px(P,i);
    if(p.x<-m||p.x>W+m||p.y<-m||p.y>H+m)s.add(i);}
  return s;
}
/* Stability (guards.check_landmark_stability). P2 is the same photo detected
   again after a 4% downscale-and-restore; null means nothing was found the
   second time, undefined means the check was not run. */
function stability(P,P2,W,H){
  if(P2===undefined)return {findings:[],drifted:new Set()};
  if(P2===null)return {findings:[{sev:"block",key:"unstable_detection"}],drifted:new Set()};
  const sc=bodyScale(P,W,H),drifted=new Set();
  if(sc<=1e-6)return {findings:[],drifted};
  for(const i of CRIT)if(dist(px(P,i),px(P2,i))/sc>C.guards.UNSTABLE_LANDMARK_FRAC)drifted.add(i);
  return {findings:drifted.size?[{sev:"warn",key:"unstable_landmarks"}]:[],drifted};
}
function guards(P,V,mets,W,H,S,others,origS){
  const out=[],oof=outOfFrame(P,W,H),g=C.guards;
  if([...oof].some(i=>CRIT.includes(i)))out.push({sev:"warn",key:"landmarks_out_of_frame"});
  const xs=P.map(p=>p[0]),ys=P.map(p=>p[1]);
  const dg=Math.hypot(Math.max(...xs)-Math.min(...xs),Math.max(...ys)-Math.min(...ys));
  for(const o of (others||[])){const d=Math.hypot(o[2]-o[0],o[3]-o[1]);
    if(dg>0&&d/dg>=g.BYSTANDER_SIZE_RATIO){out.push({sev:"block",key:"multiple_people"});break;}}
  const shm=mid(px(P,LSH),px(P,RSH)),hipm=mid(px(P,LHIP),px(P,RHIP)),ankm=mid(px(P,LANK),px(P,RANK));
  const torso=dist(shm,hipm),leg=dist(hipm,ankm);
  if(leg<=1e-6)out.push({sev:"block",key:"degenerate_geometry"});
  else{const r=torso/leg;
    if(r<g.TORSO_LEG_RATIO_MIN||r>g.TORSO_LEG_RATIO_MAX)out.push({sev:"block",key:"implausible_proportions"});}
  if(V.view==="oblique")out.push({sev:"block",key:"oblique_view"});
  if(V.view==="side"&&V.conf<0.25)out.push({sev:"warn",key:"facing_ambiguous"});
  // Deliberately NOT skipped when the ankle is out of frame, exactly as in
  // guards.check_pose_neutrality: a half-body photo's extrapolated legs are
  // what gets it rejected. An earlier port skipped these and let such photos
  // through; checking every test photo instead of six samples caught it.
  const kn=mets.knee_deviation,ts=mets.trunk_sway;
  if(kn&&kn.val>g.MAX_KNEE_FLEXION)out.push({sev:"block",key:"knee_flexed"});
  if(ts&&Math.abs(ts.val)>g.MAX_TRUNK_LEAN)out.push({sev:"block",key:"trunk_leaning"});
  if(V.view==="front"||V.view==="oblique"){
    if(!oof.has(LANK)&&!oof.has(RANK)){
      const hw=dist(px(P,LHIP),px(P,RHIP)),aw=dist(px(P,LANK),px(P,RANK));
      if(hw>1e-6&&aw/hw>g.MAX_STANCE_WIDTH_RATIO)out.push({sev:"block",key:"stance_too_wide"});
      const knees=[angI(px(P,LHIP),px(P,LKNEE),px(P,LANK)),angI(px(P,RHIP),px(P,RKNEE),px(P,RANK))].filter(a=>!isNaN(a));
      if(knees.length&&Math.max(...knees)<g.MIN_KNEE_EXTENSION_FRONT_DEG)out.push({sev:"block",key:"knees_not_extended"});
      if(Math.abs(hipm.x-ankm.x)/S>g.MAX_WEIGHT_SHIFT_FRAC)out.push({sev:"warn",key:"weight_on_one_leg"});
    }
    if((px(P,LWR).y-px(P,LHIP).y)/S<g.MIN_WRIST_BELOW_HIP_FRAC||(px(P,RWR).y-px(P,RHIP).y)/S<g.MIN_WRIST_BELOW_HIP_FRAC)
      out.push({sev:"warn",key:"arms_not_at_side"});
  }
  // guards.check_side_arms: wrists far in front of the hips = reaching or
  // leaning on something, so head and shoulders are placed by the task.
  if(V.view==="side"){const sc=bodyScale(P,W,H);
    if(sc>1e-6){const ahead=[[LWR,LHIP],[RWR,RHIP]].filter(([w])=>!oof.has(w))
        .map(([w,h])=>(px(P,w).x-px(P,h).x)*V.facing/sc);
      if(ahead.length&&Math.max(...ahead)>g.MAX_WRIST_AHEAD_OF_HIP_FRAC)out.push({sev:"block",key:"arms_reaching"});}}
  for(const k in mets){const m=mets[k];
    if(m.plane==="sagittal"&&Math.abs(m.val)>g.MAX_PLAUSIBLE_ANGLE){out.push({sev:"block",key:"implausible_reading"});break;}}
  // Absolute pixels, so judged on the photo's original resolution.
  if(V.view!=="front"&&(origS||S)<g.MIN_SUBJECT_HEIGHT_PX)out.push({sev:"warn",key:"subject_too_small"});
  return {findings:out,oof};
}
function classify(sp,v){const x=sp.direction==="positive_only"?v:Math.abs(v);
  return x>=sp.notable?"notable":(x>=sp.slight?"slight":"reference");}

/* S: {lm, w, h, others, oscale, lm2}. Mirrors assess.assess(). */
function assess(S){
  const P=S.lm,W=S.w,H=S.h,V=estimateView(P,W,H);
  const {mets,near}=computeAll(P,V);
  const {findings,oof}=guards(P,V,mets,W,H,V.scale,S.others,S.oscale);
  const st=stability(P,S.lm2,W,H);findings.push(...st.findings);
  const unavail={},unstable={};
  for(const k in mets){const idx=mets[k].idx;
    const bad=idx.filter(i=>oof.has(i));if(bad.length){unavail[k]=bad;continue;}
    const dr=idx.filter(i=>st.drifted.has(i));if(dr.length)unstable[k]=dr;}
  let blocked=findings.some(f=>f.sev==="block");
  const judged=Object.keys(mets).filter(k=>!DIAG.has(k)&&C.thresholds[k]);
  if(judged.length&&judged.every(k=>unavail[k]||unstable[k])){blocked=true;
    findings.push({sev:"block",key:"all_metrics_unavailable"});}
  const verdicts={};
  if(!blocked)for(const k in mets){
    if(DIAG.has(k)||unavail[k]||unstable[k])continue;
    const sp=C.thresholds[k];if(!sp)continue;
    const m=mets[k],band=classify(sp,m.val);
    const floored=!isNaN(m.unc)&&(sp.notable-sp.slight)>0&&m.unc>=(sp.notable-sp.slight);
    const lo=classify(sp,m.val-m.unc),hi=classify(sp,m.val+m.unc);
    const resolved=!isNaN(m.unc)&&lo===band&&hi===band&&!floored;
    verdicts[k]={band,resolved,floored,sp,m};
  }
  return {V,mets,near,findings,unavail,unstable,blocked,verdicts,P,W,H};
}

/* ---- the plain answer: port of posture/report.py ---- */
const ISSUE_ORDER=["head_over_hip","shoulder_protraction","trunk_sway","shoulder_tilt","lateral_head_shift"];
function levelFor(v){
  if(v.floored)return "not_measured";
  const m=v.m,sp=v.sp,u=isNaN(m.unc)?0:m.unc;
  const nearest=sp.direction==="positive_only"?m.val-u:(Math.abs(m.val)<=u?0:Math.abs(m.val)-u);
  const lowest=classify(sp,nearest);
  if(lowest==="notable")return "notable";
  if(lowest==="slight")return "slight";
  return v.resolved?"good":"borderline";
}
function imageSide(P,a,b){  // image-left/right of the HIGHER of two landmarks
  const pa=px(P,a),pb=px(P,b),top=pa.y<pb.y?pa:pb,other=top===pa?pb:pa;
  return top.x<other.x?"left":"right";
}
function direction(key,r){
  const m=r.mets[key];
  if(key==="trunk_sway")return {direction:m.val>0?"forward":"back"};
  if(key==="shoulder_tilt")return {side:imageSide(r.P,LSH,RSH)};
  if(key==="pelvis_tilt")return {side:imageSide(r.P,LHIP,RHIP)};
  if(key==="lateral_head_shift")return {side:m.val>0?"right":"left"};
  return {};
}
function copyFor(key,extra){
  let c=C.copy.issues[key];
  if(key==="trunk_sway")c=Object.assign({},c,c[extra.direction||"forward"]);
  const side=C.copy.sides[extra.side]||"";
  return {name:c.name,summary:c.summary.replace("{side}",side),why:c.why,tips:c.tips};
}
function partsOf(idx){
  const out=[];
  for(const i of idx)for(const [frag,part] of Object.entries(C.copy.parts))
    if(NAMES[i].includes(frag)&&!out.includes(part))out.push(part);
  return out.join("、")||"部分身体";
}
function report(r){
  const K=C.copy,view=r.V.view,other={side:"front",front:"side"}[view];
  const base={view,disclaimer:K.disclaimer,
    other_view:other?Object.assign({view:other},K.other_view[other]):null};
  const empty={issues:[],borderline:[],good:[],not_measured:[],photo_tips:[]};
  if(r.blocked){
    const seen=new Set(),retake=[];
    for(const f of r.findings){if(f.sev!=="block"||seen.has(f.key))continue;seen.add(f.key);
      const c=K.retake[f.key];if(c)retake.push(Object.assign({key:f.key},c));}
    if(!retake.length)retake.push({key:"unknown",title:"这张照片没法分析",tip:"请换一张从头到脚、站直拍的全身照。"});
    return Object.assign(base,empty,{status:"retake",retake});
  }
  const issues=[],borderline=[],good=[],nm=[];
  for(const key of ISSUE_ORDER){
    if(!K.issues[key])continue;
    const goodName=K.issues[key].good;
    if(r.unavail[key]){nm.push({key,name:goodName,reason:K.not_measured.out_of_frame.replace("{parts}",partsOf(r.unavail[key]))});continue;}
    if(r.unstable[key]){nm.push({key,name:goodName,reason:K.not_measured.unstable});continue;}
    const v=r.verdicts[key];if(!v)continue;
    const lvl=levelFor(v);
    if(lvl==="not_measured"){nm.push({key,name:goodName,reason:K.not_measured.floored});continue;}
    if(lvl==="good"){good.push({key,name:goodName});continue;}
    const extra=direction(key,r);
    const item=Object.assign({key,level:lvl,level_label:K.levels[lvl],landmarks:r.mets[key].idx.slice()},extra,copyFor(key,extra));
    (lvl==="borderline"?borderline:issues).push(item);
  }
  if(!(issues.length||borderline.length||good.length))
    return Object.assign(base,empty,{status:"retake",not_measured:nm,
      retake:[Object.assign({key:"nothing_judged"},K.retake.unstable_detection)]});
  issues.sort((a,b)=>(a.level==="notable"?0:1)-(b.level==="notable"?0:1));
  const tips=r.findings.filter(f=>f.sev==="warn"&&K.photo_tips[f.key]).map(f=>K.photo_tips[f.key]);
  return Object.assign(base,{status:"ok",retake:[],issues,borderline,good,not_measured:nm,photo_tips:tips});
}
if(typeof module!=="undefined")module.exports={assess,report,estimateView,EDGES,NAMES};
